### ISSUE TITLE
How about using PHPDoc blocks?

### ISSUE THREAD

**Issue by szepeviktor** [DaveLiddament/phpstan-rule-test-helper#1]
```php
$item->updateName("world");  // ERROR

/**
 * @phpstan-error Example error occured!
 */
$item->updateName("world");
```
It can be read by built-in reflections.

What do you think?

**Comment by DaveLiddament** [comment]
What would be the benefits of comments in docblocks over `// ERROR`? 

Ordinarily I'd go with docblocks, but in this case it might be easier to read inline?

**Comment by szepeviktor** [comment]
I thought parsing something following a standard has more future.
